# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  pingvin-share-x = {
    pname = "pingvin-share-x";
    version = "v1.22.3";
    src = fetchFromGitHub {
      owner = "smp46";
      repo = "pingvin-share-x";
      rev = "v1.22.3";
      fetchSubmodules = false;
      sha256 = "sha256-xtsI9Ow7K/9pXEZdvBICF5aWAa+Hh7VfNUTwejz4Xno=";
    };
  };
  pingvin-share-x-beta = {
    pname = "pingvin-share-x-beta";
    version = "v2.0.0-beta.2";
    src = fetchFromGitHub {
      owner = "smp46";
      repo = "pingvin-share-x";
      rev = "v2.0.0-beta.2";
      fetchSubmodules = false;
      sha256 = "sha256-WfHk/WFSd5toObGmzgL2s0ir5Eg/3PTROa8NBxsF05M=";
    };
  };
}
