# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  windscribe = {
    pname = "windscribe";
    version = "v2.23.9";
    src = fetchFromGitHub {
      owner = "Windscribe";
      repo = "Desktop-App";
      rev = "v2.23.9";
      fetchSubmodules = false;
      sha256 = "sha256-VmhIDGXKQnwjuQewQuGII/BjqswhWuudkQNmP7F/NvQ=";
    };
  };
  wsnet = {
    pname = "wsnet";
    version = "1.5.20";
    src = fetchFromGitHub {
      owner = "Windscribe";
      repo = "wsnet";
      rev = "1.5.20";
      fetchSubmodules = false;
      sha256 = "sha256-2PGaoE0p3kr50rdVtvUnG5qdYERBuF5LF88qboxLZgc=";
    };
  };
  wstunnel = {
    pname = "wstunnel";
    version = "v1.0.6";
    src = fetchFromGitHub {
      owner = "Windscribe";
      repo = "wstunnel";
      rev = "v1.0.6";
      fetchSubmodules = false;
      sha256 = "sha256-WGLgZStXzZjseMumxQ2D1UFSdE3xZpYE6g5omPw6swQ=";
    };
  };
}
