# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  picr = {
    pname = "picr";
    version = "1.6.2";
    src = fetchFromGitHub {
      owner = "isaacinsoll";
      repo = "picr";
      rev = "1.6.2";
      fetchSubmodules = false;
      sha256 = "sha256-UrIA4oZ2INSWziy23HBSRmutceHjwcl3YZIaQaXi2Mw=";
    };
  };
}
