# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  blockNvim = {
    pname = "blockNvim";
    version = "6fb969ab12579e58b9379aa51933cad4a466cf75";
    src = fetchgit {
      url = "https://github.com/HampusHauffman/block.nvim";
      rev = "6fb969ab12579e58b9379aa51933cad4a466cf75";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-dqi4srdtm7TNsFPNcGpV8iwyTL+ov4AEfuQpVnikiYI=";
    };
    date = "2023-10-10";
  };
  clearActionNvim = {
    pname = "clearActionNvim";
    version = "2854c3fda5720c7e53b5a9537774fae212224484";
    src = fetchgit {
      url = "https://github.com/luckasRanarison/clear-action.nvim";
      rev = "2854c3fda5720c7e53b5a9537774fae212224484";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-9WVYHQNBKxMqhCzI8UBuZGe4gX6gB3/V5kIc/sPB3TQ=";
    };
    date = "2024-05-17";
  };
  cocElixir = {
    pname = "cocElixir";
    version = "a48b9c8fd8651fc3886b16f5c2fc367d91f4cffc";
    src = fetchgit {
      url = "https://github.com/elixir-lsp/coc-elixir";
      rev = "a48b9c8fd8651fc3886b16f5c2fc367d91f4cffc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-xHCX3KWtA2+YrGRgua+vdI+8/yEJQjnZS0u82eHhuqw=";
    };
    date = "2022-04-30";
  };
  cocLightbulb = {
    pname = "cocLightbulb";
    version = "877183739b3609238195d2f85c0b11b04a978eb8";
    src = fetchgit {
      url = "https://github.com/xiyaowong/coc-lightbulb-";
      rev = "877183739b3609238195d2f85c0b11b04a978eb8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-xQd0tNkKFH/BDNPoeC1jEr2zcR0L5ICxjIwhuTkC4P8=";
    };
    date = "2024-03-20";
  };
  cspellNvim = {
    pname = "cspellNvim";
    version = "5feecef8d109f5460c576596aba44a6253127aa4";
    src = fetchgit {
      url = "https://github.com/davidmh/cspell.nvim";
      rev = "5feecef8d109f5460c576596aba44a6253127aa4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-NTgIaEWqtubjFEfIrw8sKTjhNbnmJ1In0OcddRg5W0w=";
    };
    date = "2025-12-17";
  };
  direnvVim = {
    pname = "direnvVim";
    version = "ab2a7e08dd630060cd81d7946739ac7442a4f269";
    src = fetchgit {
      url = "https://github.com/direnv/direnv.vim";
      rev = "ab2a7e08dd630060cd81d7946739ac7442a4f269";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Lwwm95UEkS8Q0Qsoh10o3sFn48wf7v7eCX/FJJV1HMI=";
    };
    date = "2023-12-02";
  };
  gitNvim = {
    pname = "gitNvim";
    version = "7cfb3080c68125dbf6b7ee129f3108fdb275c4dd";
    src = fetchgit {
      url = "https://github.com/dinhhuy258/git.nvim";
      rev = "7cfb3080c68125dbf6b7ee129f3108fdb275c4dd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-cv7AjXZiSEwvPwlBn9rTFFA6lMAZOcQ8K6iCVm6BANI=";
    };
    date = "2026-03-08";
  };
  guihuaLua = {
    pname = "guihuaLua";
    version = "f8e06bd8a26dee3377d63c2adf1e57cdb58ac474";
    src = fetchgit {
      url = "https://github.com/ray-x/guihua.lua";
      rev = "f8e06bd8a26dee3377d63c2adf1e57cdb58ac474";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-lupDg/yt75164H8zQs/HTKqC3Y1FnQCzoMq90nwapO8=";
    };
    date = "2026-05-27";
  };
  indentmini = {
    pname = "indentmini";
    version = "38572ce5a7a064a5deb89d6d861b7c40fc929ab1";
    src = fetchgit {
      url = "https://github.com/nvimdev/indentmini.nvim";
      rev = "38572ce5a7a064a5deb89d6d861b7c40fc929ab1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-XcoBNrvFMmEMcgrknDg/HnxRNssom6vLeOKiu1qJKBo=";
    };
    date = "2026-01-04";
  };
  inlayHints = {
    pname = "inlayHints";
    version = "006b0898f5d3874e8e528352103733142e705834";
    src = fetchgit {
      url = "https://github.com/simrat39/inlay-hints.nvim";
      rev = "006b0898f5d3874e8e528352103733142e705834";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-cDWx08N+NhN5Voxh8f7RGzerbAYB5FHE6TpD4/o/MIQ=";
    };
    date = "2022-08-12";
  };
  kittyScrollback = {
    pname = "kittyScrollback";
    version = "53fd294658941719d7622471f28e70179d6737a6";
    src = fetchgit {
      url = "https://github.com/mikesmithgh/kitty-scrollback.nvim";
      rev = "53fd294658941719d7622471f28e70179d6737a6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-PN9mzliyoIQ5BhG57p7obhsbDaLkbbWdltLLNL1Ti20=";
    };
    date = "2026-05-13";
  };
  miniMove = {
    pname = "miniMove";
    version = "a776027e68fe763987a0132d59877d651a7c0130";
    src = fetchgit {
      url = "https://github.com/echasnovski/mini.move";
      rev = "a776027e68fe763987a0132d59877d651a7c0130";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-f+MHsSCR9Y2gVV7X/o+HIVzbwZZVG7eL7Q9XILbqAsc=";
    };
    date = "2026-05-12";
  };
  neoai = {
    pname = "neoai";
    version = "d502953da17ba67a1dcb703c31194533fc664092";
    src = fetchgit {
      url = "https://github.com/bryley/neoai.nvim";
      rev = "d502953da17ba67a1dcb703c31194533fc664092";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-72njaioZ1vegP+k6Lv+PaVgPcE8aPwjvpQv4Az1m/HQ=";
    };
    date = "2025-07-25";
  };
  neotestGtest = {
    pname = "neotestGtest";
    version = "b66f1d33cbf3b37b9803e6bc7ef47ac60eba86b1";
    src = fetchgit {
      url = "https://github.com/alfaix/neotest-gtest";
      rev = "b66f1d33cbf3b37b9803e6bc7ef47ac60eba86b1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-3za8pI1WmKprBhEVcf8P6rWtsc3pe55EqshN7xDIIQY=";
    };
    date = "2025-09-26";
  };
  noneLs = {
    pname = "noneLs";
    version = "01f8e62ea11603e59ad9ff7afcfa94fd183f76d6";
    src = fetchgit {
      url = "https://github.com/nvimtools/none-ls.nvim";
      rev = "01f8e62ea11603e59ad9ff7afcfa94fd183f76d6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Amz3UFxET/+poFUm+ldyPEdl9u9/DDMarvgF+AleC/U=";
    };
    date = "2026-06-02";
  };
  noneLsExtras = {
    pname = "noneLsExtras";
    version = "27681d797a26f1b4d6119296df42f5204c88a2dc";
    src = fetchgit {
      url = "https://github.com/nvimtools/none-ls-extras.nvim";
      rev = "27681d797a26f1b4d6119296df42f5204c88a2dc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-GZLT8X1eLeSkiV5EN1nOkCQg5nwNATURi/KMj90i40I=";
    };
    date = "2026-06-06";
  };
  nvimDapReplHighlights = {
    pname = "nvimDapReplHighlights";
    version = "f31deba47fe3ee6ff8d2f13d9dbd06b2d1ae06b5";
    src = fetchgit {
      url = "https://github.com/LiadOz/nvim-dap-repl-highlights";
      rev = "f31deba47fe3ee6ff8d2f13d9dbd06b2d1ae06b5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-1QjmDy4v1AvNs5F4V8C3Lu7CVQH+uOV8gU855oz2IjY=";
    };
    date = "2025-10-07";
  };
  nvimEmmet = {
    pname = "nvimEmmet";
    version = "cde4fb2968704aae5c18b7f8a9bc2508767bb78d";
    src = fetchgit {
      url = "https://github.com/olrtg/nvim-emmet";
      rev = "cde4fb2968704aae5c18b7f8a9bc2508767bb78d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-LgKASQ1xBL8ugxK1g4R3BLQ3ha05cFtZaSYvd2Hy73c=";
    };
    date = "2024-05-31";
  };
  oneSmallStep = {
    pname = "oneSmallStep";
    version = "1af6ffb9b5229a856e8090fa2f690e0931a5aace";
    src = fetchgit {
      url = "https://github.com/jbyuki/one-small-step-for-vimkind";
      rev = "1af6ffb9b5229a856e8090fa2f690e0931a5aace";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-IqyNgMf8hH2KpRY8gTrqREMCZwMNfDRdH/joqhGhjxI=";
    };
    date = "2026-01-12";
  };
  pfpVim = {
    pname = "pfpVim";
    version = "a7a598e91408f9edb01089ecf44bae72bb7d197b";
    src = fetchgit {
      url = "https://github.com/d0c-s4vage/pfp-vim";
      rev = "a7a598e91408f9edb01089ecf44bae72bb7d197b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-K1JwjVYj16aB7sH/9xsqHyniuX8cRQoonfVa/543hLY=";
    };
    date = "2019-09-21";
  };
  sgNvim = {
    pname = "sgNvim";
    version = "775f22b75a9826eabf69b0094dd1d51d619fe552";
    src = fetchgit {
      url = "https://github.com/sourcegraph/sg.nvim";
      rev = "775f22b75a9826eabf69b0094dd1d51d619fe552";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-i5g+pzxB8pAORLbr1wlYWUTsrJJmVj9UwlCg8pU3Suw=";
    };
    date = "2025-01-21";
  };
  stayCentered = {
    pname = "stayCentered";
    version = "e1a63ccaf2584e97c0ef8e64f9654c9a80d983f6";
    src = fetchgit {
      url = "https://github.com/arnamak/stay-centered.nvim";
      rev = "e1a63ccaf2584e97c0ef8e64f9654c9a80d983f6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-TIiv0pwBkwn7n1JFVqgcruKZ69OdxdEId4ca+M5hZ9k=";
    };
    date = "2024-11-12";
  };
  telescopeDocker = {
    pname = "telescopeDocker";
    version = "4219840291d9e3e64f6b8eefa11e8deb14357581";
    src = fetchgit {
      url = "https://github.com/lpoto/telescope-docker.nvim";
      rev = "4219840291d9e3e64f6b8eefa11e8deb14357581";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-nOMPWVlQR4jRdIt7UDADxl1p3lkx7+fVVboF/6wZW1g=";
    };
    date = "2023-06-05";
  };
  tsSoftwareLicenses = {
    pname = "tsSoftwareLicenses";
    version = "20f3f1e374be87b7a569995b6168e943e14ea7a6";
    src = fetchgit {
      url = "https://github.com/chip/telescope-software-licenses.nvim";
      rev = "20f3f1e374be87b7a569995b6168e943e14ea7a6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-U8OZ11VJ5EXXnefE7J4/TW2nqBfLdtZauEKi2IINIuM=";
    };
    date = "2026-02-22";
  };
  vimBeGood = {
    pname = "vimBeGood";
    version = "0ae3de14eb8efc6effe7704b5e46495e91931cc5";
    src = fetchgit {
      url = "https://github.com/ThePrimeagen/vim-be-good";
      rev = "0ae3de14eb8efc6effe7704b5e46495e91931cc5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-yrNZV90yiHIxw0OMSSvi5SMApR2oFT8EpvF6TiUlC88=";
    };
    date = "2024-12-04";
  };
  virtColumn = {
    pname = "virtColumn";
    version = "b87e3e0864211a32724a2ebf3be37e24e9e2fa99";
    src = fetchgit {
      url = "https://github.com/lukas-reineke/virt-column.nvim";
      rev = "b87e3e0864211a32724a2ebf3be37e24e9e2fa99";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ozrjz34YIlDziuc9KLYM9zikTlg2YKYlIewapzN/nlY=";
    };
    date = "2024-11-12";
  };
  wtfNvim = {
    pname = "wtfNvim";
    version = "010c779f84a151477f74398c8ead71e42d70b816";
    src = fetchgit {
      url = "https://github.com/piersolenski/wtf.nvim";
      rev = "010c779f84a151477f74398c8ead71e42d70b816";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-rVkZ5fkqts7bB87oxO8N6bB1m43CrpP2kbLSJHZUsH4=";
    };
    date = "2026-06-02";
  };
}
