# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  projectsend = {
    pname = "projectsend";
    version = "2.7.0";
    src = fetchurl {
      url = "https://github.com/projectsend/projectsend/releases/download/v2.7.0/projectsend-2.7.0.zip";
      sha256 = "sha256-eQBLKrvExjpCbuMLUiEUZ9YsAEHOnUlGSA2VySDtg5Q=";
    };
  };
}
