# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  projectsend = {
    pname = "projectsend";
    version = "2.4.1";
    src = fetchurl {
      url = "https://github.com/projectsend/projectsend/releases/download/v2.4.1/projectsend-2.4.1.zip";
      sha256 = "sha256-xYP7TKB0Z8tyLKp6IljcQmiQYPQimtCWY/XA8uJlSsU=";
    };
  };
}
