# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  projectsend = {
    pname = "projectsend";
    version = "2.5.0";
    src = fetchurl {
      url = "https://github.com/projectsend/projectsend/releases/download/v2.5.0/projectsend-2.5.0.zip";
      sha256 = "sha256-EHsB2lacE6YiYr4MkAPe9ClAT11x7HdkvxwAJc18dqw=";
    };
  };
}
