# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  affine-mcp-server = {
    pname = "affine-mcp-server";
    version = "v3.1.0";
    src = fetchFromGitHub {
      owner = "DAWNCR0W";
      repo = "affine-mcp-server";
      rev = "v3.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-8gQXVDNsOHhGN078XADIeO420G0N+5Z8lRxFwNDRURk=";
    };
  };
  affine-server = {
    pname = "affine-server";
    version = "0.27.3";
    src = dockerTools.pullImage {
      imageName = "ghcr.io/toeverything/affine";
      imageDigest = "sha256:d9d145f9f47b862d1fa96e2a887052b5762846237f75fbb077be990ef646e05c";
      sha256 = "sha256-4RPZClicwO1oWSwJRt5gWGLPvWniWBkHN9yjgHA+ciY=";
      finalImageTag = "0.27.3";
      os = "linux";
      arch = "amd64";
    };
  };
  affine-server-arm64 = {
    pname = "affine-server-arm64";
    version = "0.27.3";
    src = dockerTools.pullImage {
      imageName = "ghcr.io/toeverything/affine";
      imageDigest = "sha256:d9d145f9f47b862d1fa96e2a887052b5762846237f75fbb077be990ef646e05c";
      sha256 = "sha256-rWWnXDqQytDER9cQzOkDZ74q8+dcCx58XxhXbjyajDI=";
      finalImageTag = "0.27.3";
      os = "linux";
      arch = "arm64";
    };
  };
  electron-mail = {
    pname = "electron-mail";
    version = "5.3.8";
    src = fetchurl {
      url = "https://github.com/vladimiry/ElectronMail/releases/download/v5.3.8/electron-mail-5.3.8-linux-x86_64.AppImage";
      sha256 = "sha256-twqB1D3zLlZJuxQWD4dGF70w57yYv6i3abGBidERsss=";
    };
  };
  freebuff-darwin-arm64 = {
    pname = "freebuff-darwin-arm64";
    version = "0.0.137";
    src = fetchurl {
      url = "https://github.com/CodebuffAI/codebuff-community/releases/download/freebuff-v0.0.137/freebuff-darwin-arm64.tar.gz";
      sha256 = "sha256-qsMRV5SmbkWfXkCOxcPw7hLerrvOS8J12EiofvospKs=";
    };
  };
  freebuff-linux-arm64 = {
    pname = "freebuff-linux-arm64";
    version = "0.0.137";
    src = fetchurl {
      url = "https://github.com/CodebuffAI/codebuff-community/releases/download/freebuff-v0.0.137/freebuff-linux-arm64.tar.gz";
      sha256 = "sha256-M8QrzCzc8u9Kt5F/gFhPboYPjkSuWJ6MmuLoFzRhll8=";
    };
  };
  freebuff-linux-x64 = {
    pname = "freebuff-linux-x64";
    version = "0.0.137";
    src = fetchurl {
      url = "https://github.com/CodebuffAI/codebuff-community/releases/download/freebuff-v0.0.137/freebuff-linux-x64.tar.gz";
      sha256 = "sha256-GzlDadOvizBOTlILi6+qThAQUol9Xs2PokONTHeOvIw=";
    };
  };
  workstyle = {
    pname = "workstyle";
    version = "dae15018c84c4f0feaf498d3676271ca0e3bec44";
    src = fetchgit {
      url = "https://github.com/pierrechevalier83/workstyle";
      rev = "dae15018c84c4f0feaf498d3676271ca0e3bec44";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-YcAn2oIVegAHa/mpqryRR1OIIAoJvCv+IiHB7s5mZOY=";
    };
    date = "2025-10-19";
  };
}
