# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  workstyle = {
    pname = "workstyle";
    version = "dae15018c84c4f0feaf498d3676271ca0e3bec44";
    src = fetchgit {
      url = "https://github.com/pierrechevalier83/workstyle";
      rev = "dae15018c84c4f0feaf498d3676271ca0e3bec44";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-YcAn2oIVegAHa/mpqryRR1OIIAoJvCv+IiHB7s5mZOY=";
    };
    date = "2025-10-19";
  };
}
