# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  affine-mcp-server = {
    pname = "affine-mcp-server";
    version = "v3.2.2";
    src = fetchFromGitHub {
      owner = "DAWNCR0W";
      repo = "affine-mcp-server";
      rev = "v3.2.2";
      fetchSubmodules = false;
      sha256 = "sha256-6iZ6IsKHftCJjVhAumtKyt5cYwOZuOz6npULB29xX+I=";
    };
    extract = {
      "package-lock.json" = ./. + "/sha256-6iZ6IsKHftCJjVhAumtKyt5cYwOZuOz6npULB29xX+I=/package-lock.json";
      "package.json" = ./. + "/sha256-6iZ6IsKHftCJjVhAumtKyt5cYwOZuOz6npULB29xX+I=/package.json";
    };
  };
  affine-server = {
    pname = "affine-server";
    version = "0.27.4";
    src = dockerTools.pullImage {
      imageName = "ghcr.io/toeverything/affine";
      imageDigest = "sha256:b649f5ce2384ffdf13c23bccf81d759e15973d59d0b0058af65d895a84373099";
      sha256 = "sha256-PtBPprgsFmNAiEnYeCNMzYxYYf/WTqY2Vd4oojhRt64=";
      finalImageTag = "0.27.4";
      os = "linux";
      arch = "amd64";
    };
  };
  affine-server-arm64 = {
    pname = "affine-server-arm64";
    version = "0.27.4";
    src = dockerTools.pullImage {
      imageName = "ghcr.io/toeverything/affine";
      imageDigest = "sha256:b649f5ce2384ffdf13c23bccf81d759e15973d59d0b0058af65d895a84373099";
      sha256 = "sha256-ueQh66W79jggD0+FNJ83gH9gqej7FCkaUHAzdYV0nTI=";
      finalImageTag = "0.27.4";
      os = "linux";
      arch = "arm64";
    };
  };
  electron-mail = {
    pname = "electron-mail";
    version = "5.3.8";
    src = fetchurl {
      url = "https://github.com/vladimiry/ElectronMail/releases/download/v5.3.8/electron-mail-5.3.8-linux-x86_64.AppImage";
      sha256 = "sha256-twqB1D3zLlZJuxQWD4dGF70w57yYv6i3abGBidERsss=";
    };
  };
  figmaqml = {
    pname = "figmaqml";
    version = "v3.2.1";
    src = fetchFromGitHub {
      owner = "mmertama";
      repo = "FigmaQML";
      rev = "v3.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-Qvi3iw/2dNM/tGjzPL0A46kyWCvMREpMxA1YhqB0oRI=";
    };
  };
  freebuff-darwin-arm64 = {
    pname = "freebuff-darwin-arm64";
    version = "0.0.154";
    src = fetchurl {
      url = "https://github.com/CodebuffAI/codebuff-community/releases/download/freebuff-v0.0.154/freebuff-darwin-arm64.tar.gz";
      sha256 = "sha256-5UBXlcqymazb20SboiFCTyyLniz9WivGfJUUEuAwKCU=";
    };
  };
  freebuff-linux-arm64 = {
    pname = "freebuff-linux-arm64";
    version = "0.0.154";
    src = fetchurl {
      url = "https://github.com/CodebuffAI/codebuff-community/releases/download/freebuff-v0.0.154/freebuff-linux-arm64.tar.gz";
      sha256 = "sha256-1w32fxSPgqOjgyeqiUkVaXq+MpMNTBhVQ0A1/mwuzL4=";
    };
  };
  freebuff-linux-x64 = {
    pname = "freebuff-linux-x64";
    version = "0.0.154";
    src = fetchurl {
      url = "https://github.com/CodebuffAI/codebuff-community/releases/download/freebuff-v0.0.154/freebuff-linux-x64.tar.gz";
      sha256 = "sha256-82+GA43pI5OBedfD3Y+EVOXfMPZKWvefjw3l0hMc9hQ=";
    };
  };
  powertop = {
    pname = "powertop";
    version = "0048a3573077c795bf5bfe1de6c44947803f7b81";
    src = fetchgit {
      url = "https://github.com/fenrus75/powertop";
      rev = "0048a3573077c795bf5bfe1de6c44947803f7b81";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-N3rrMl5gJVfc6YVlBPQNwyXtZgYQO+FKKXEoM8VNLAA=";
    };
    date = "2026-08-18";
  };
  workstyle = {
    pname = "workstyle";
    version = "dae15018c84c4f0feaf498d3676271ca0e3bec44";
    src = fetchgit {
      url = "https://github.com/pierrechevalier83/workstyle";
      rev = "dae15018c84c4f0feaf498d3676271ca0e3bec44";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-YcAn2oIVegAHa/mpqryRR1OIIAoJvCv+IiHB7s5mZOY=";
    };
    date = "2025-10-19";
  };
}
